name: Agenda Viewer

on:
  push:
    branches: [ master ]  
    paths:
      - /**
  pull_request:
    branches: [ master ]
    paths:
      - /**

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: docker login
      env:        
        CR_USERNAME: ${{ secrets.CR_USERNAME }}
        PAT: ${{ secrets.PAT }}
      run: |
        echo $PAT | docker login https://ghcr.io -u $CR_USERNAME --password-stdin
    - name: build agenda-viewer Docker image 
      run: |
        docker build -f ./agenda-viewer/Calendar.AgendaViewer.WebApi/Dockerfile --pull --rm -t ghcr.io/${{ secrets.CR_USERNAME }}/calendar/agenda-viewer:${GITHUB_SHA} .
    - name: push agenda-viewer to GitHub Packages
      run: |
        docker push ghcr.io/${{ secrets.CR_USERNAME }}/calendar/agenda-viewer:${GITHUB_SHA}