name: Front End

on:
  push:
    branches: [ master ]  
    paths:
      - /**
  pull_request:
    branches: [ master ]
    paths:
      - /**

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: docker login
      env:        
        CR_USERNAME: ${{ secrets.CR_USERNAME }}
        PAT: ${{ secrets.PAT }}
      run: |
        echo $PAT | docker login https://ghcr.io -u $CR_USERNAME --password-stdin
    - name: build front-end Docker image 
      run: |
        docker build -f ./front-end/Calendar.WebApp/Dockerfile --pull --rm -t ghcr.io/${{ secrets.CR_USERNAME }}/calendar/front-end:${GITHUB_SHA} .
    - name: push front-end to GitHub Packages
      run: |
        docker push ghcr.io/${{ secrets.CR_USERNAME }}/calendar/front-end:${GITHUB_SHA}